# Generated by Django 3.2.7 on 2021-09-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_reviewgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewgroup',
            name='group_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
